name: Build & Deploy Site

on:
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install deps (optional)
        run: |
          python -m pip install --upgrade pip
          # 你的项目如果需要 jieba（历史版本用过），这里装上；没用到也不影响
          pip install jieba || true

      # 若仓库里存在 scripts/build_site.py 就运行；没有就跳过
      - name: Build site (if present)
        if: ${{ hashFiles('scripts/build_site.py') != '' }}
        run: python scripts/build_site.py

      # 关键：生成 site/index/tree.json，供前端 app.js 读取
      - name: Build tree.json (v0.24)
        run: python scripts/tree_build.py

      # 发布 ./site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
