name: Build & Deploy Site

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip

      - name: Build site indexes
        run: |
          python scripts/build_site.py || true
          # Always ensure index dir exists to avoid 404 at runtime
          mkdir -p site/index
          test -f site/index/docs.json || echo '{"docs":[]}' > site/index/docs.json
          test -f site/index/tree.json || echo '[]' > site/index/tree.json
          test -f site/index/route.json || echo '{"mode":"single","files":["shard_all.json"]}' > site/index/route.json
          test -f site/index/shard_all.json || echo '{"postings":{}}' > site/index/shard_all.json

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
